//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 
namespace ATTi.TMail.StrongMail
{
	using System.Diagnostics;
	using System.Web.Services;
	using System.ComponentModel;
	using System.Web.Services.Protocols;
	using System;
	using System.Xml.Serialization;

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Web.Services.WebServiceBindingAttribute(Name = "strongmailBinding", Namespace = "http://strongmail.com/soap/strongmail.wsdl")]
	public partial class EasBatchApi : System.Web.Services.Protocols.SoapHttpClientProtocol
	{

		private System.Threading.SendOrPostCallback executeOperationCompleted;

		/// <remarks/>
		/// 
		public EasBatchApi(string uri)
		{
			if (!string.IsNullOrEmpty(uri))
				this.Url = uri;

		}
		public EasBatchApi()
		{
			this.Url = "http://mailhub1.yellowpages.com:9000/SOAP/sm-client-v2";
		}

		/// <remarks/>
		public event executeCompletedEventHandler executeCompleted;

		/// <remarks/>
		[System.Web.Services.Protocols.SoapRpcMethodAttribute("strongmail:strongmailPortType#execute", RequestNamespace = "", ResponseNamespace = "")]
		[return: System.Xml.Serialization.SoapElementAttribute("soapVal")]
		public string execute(string smIn)
		{
			object[] results = this.Invoke("execute", new object[] {
                        smIn});
			return ((string)(results[0]));
		}

		/// <remarks/>
		public System.IAsyncResult Beginexecute(string smIn, System.AsyncCallback callback, object asyncState)
		{
			return this.BeginInvoke("execute", new object[] {
                        smIn}, callback, asyncState);
		}

		/// <remarks/>
		public string Endexecute(System.IAsyncResult asyncResult)
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}

		/// <remarks/>
		public void executeAsync(string smIn)
		{
			this.executeAsync(smIn, null);
		}

		/// <remarks/>
		public void executeAsync(string smIn, object userState)
		{
			if ((this.executeOperationCompleted == null))
			{
				this.executeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnexecuteOperationCompleted);
			}
			this.InvokeAsync("execute", new object[] {
                        smIn}, this.executeOperationCompleted, userState);
		}

		private void OnexecuteOperationCompleted(object arg)
		{
			if ((this.executeCompleted != null))
			{
				System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
				this.executeCompleted(this, new executeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
			}
		}

		/// <remarks/>
		public new void CancelAsync(object userState)
		{
			base.CancelAsync(userState);
		}
	}

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
	public delegate void executeCompletedEventHandler(object sender, executeCompletedEventArgs e);

	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	public partial class executeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
	{

		private object[] results;

		internal executeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
			base(exception, cancelled, userState)
		{
			this.results = results;
		}

		/// <remarks/>
		public string Result
		{
			get
			{
				this.RaiseExceptionIfNecessary();
				return ((string)(this.results[0]));
			}
		}
	}
}
